- .idea/jsLibraryMappings.xml
- .jshintrc
- lib/convert.js
- lib/gltf.js
- lib/mtl.js
- lib/obj.js
I added support for loading obj's with file streams to handle loading large models like the power plant (https://github.com/AnalyticalGraphicsInc/OBJ2GLTF/issues/2). Node doesn't seem to allow strings above ~192MB, so if the buffer is too large I export it to a .bin file instead of embedding the base64 string. The gltf-pipeline is not really equipped for huge files like this either so I only use the `addDefaults` stage just for generating the shaders. The gltf-pipeline also needs to export separate resources to get around the string size bug.
> Read obj with streams and handle large buffers

- CHANGES.md
- package.json
For #25 
This PR just marks the next npm publish which will change the line-endings of any bin scripts to LF.
> Update version for line-ending fix

- .gitignore
- .npmignore
- .travis.yml
- CHANGES.md
- LICENSE.md
- README.md
- gulpfile.js
- package.json
* Bumped to 0.1.7
* Updated travis (@pjcozzi forgot to wait for this one - but it fixes https://github.com/AnalyticalGraphicsInc/obj2gltf/issues/40)
* Using ^ in package.json
* Added jsdoc
* Upgrade gltf-pipeline
The travis build is failing at `JasmineSpecReporter is not a constructor` but succeeds for master. I may need to downgrade `jasmine-spec-reporter`.
I'll publish once this PR is in.
> Update gltf-pipeline and general project cleanup

- lib/obj2gltf.js
For #71 
This is for proper error reporting when `--bypassPipeline` and `-b` are both set, which isn't allowed right now.
I don't think this counts as incorrect usage of the library, so I'm rejecting the promise instead of throwing an error. Otherwise the error is not caught in `bin/obj2gltf.js`.
If this should still be a `DeveloperError`, I can wrap the `obj2gltf` call in `bin/obj2gltf.js` in a try-catch.
> Return Promise.reject instead of throwing error

- lib/loadMtl.js
- specs/data/box-complex-material/box-complex-material.mtl
Fixes https://github.com/AnalyticalGraphicsInc/obj2gltf/issues/76
Fixes parsing the `Tr` property. By convention a value of 0 means opaque and 1 means translucent, I had it backwards.
> Treat alpha as 1.0 - Tr

- lib/loadImage.js
- lib/obj2gltf.js
- lib/writeUris.js
- package.json
- specs/lib/createGltfSpec.js
- specs/lib/obj2gltfSpec.js
A few npm dependencies were major versions behind, so this updates `yargs`, `fs-extra`, and `jasmin-spec-reporter` to their latest versions.
The major change here is `fs-extra`, which now has promise implementations of all functions by default, this means there's no reason to manually `Promisify` a function any more, the result is less code overall.
There is one important edge case, `fs-extra` uses built-in native Node promises, which do not have a `finally` function. If you start a promise change with an `fs-extra` function, you need to wrap it in `Promise.resolve` in order to make use of finally at the end (assuming you are using finally at all, if not you don't need to worry about it. The upside is that your code will always error if you forget to do this.
> Update npm dependencies

- CHANGES.md
- lib/createGltf.js
- specs/lib/createGltfSpec.js
> make mip-mapping on by default

- .gitignore
- README.md
- gulpfile.js
- package.json
Simple switch from `Istanbul` to [`nyc`](https://github.com/istanbuljs/nyc) for code coverage.
> Replace Istanbul with nyc

- CHANGES.md
- lib/createGltf.js
- lib/obj2gltf.js
- specs/lib/createGltfSpec.js
Fix for a bug reported on the forum: https://groups.google.com/forum/#!topic/cesium-dev/b3iU1vlmaxo
* obj2gltf outputs `KHR_materials_common` which gltf-pipeline can generate shaders for
* If the model has no normals it sets the emission color instead of the diffuse color. This is needed for the [constant lighting equation](https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_common#constant)
* But if `--generateNormals` is set, gltf-pipeline will recreate the shaders again but this time expects the diffuse to exist.
* So instead this checks if normals will be regenerated before swapping the emission and diffuse.
I consider this just a bandaid for the time being and is more of a gltf-pipeline problem. Once gltf 2.0 is in full force this also won't be an issue.
> Keep diffuse intact so that shader generation for generateNormals works

- .eslintignore
- .gitignore
- .travis.yml
- gulpfile.js
- lib/obj2gltf.js
- package.json
Move from `gulp-eslint`to a simple CLI invocation of ESLint. This allows for caching and drastically increases the speed of running `npm run eslint`. In addition, bump `eslint-cesium-config` to 2.0.0.
> Switch from gulp-eslint to the ESLint CLI

- LICENSE.md
- lib/readLines.js
- package.json
Node has built in functions for reading lines from a file, so there's no need to depend on `event-stream` just for it.
> Remove dependency on event-stream

- CHANGES.md
- lib/loadMtl.js
- lib/loadObj.js
- specs/lib/loadMtlSpec.js
At some point during the 2.0 refactor I dropped support for the `CONSTANT` lighting mode for `KHR_materials_common`, but it is worth adding back. The model just needs to pass along whether it has normals.
This is for https://github.com/AnalyticalGraphicsInc/cesium/issues/5835.
@shehzan10 can you review?
> Constant lighting added back to materialsCommon

- .gitattributes
- .gitignore
- .npmignore
- .travis.yml
- lib/writeGltf.js
- package.json
Updated so Travis runs on Node 8 and upgraded packages.
> Node 8 upgrade

- lib/loadMtl.js
Fixes #112 
The diffuse texture is now guaranteed to load first.
Before if any other texture referred to the same path as the diffuse texture it would load it without checking for transparency.
@PrincessGod could you test this branch?
> Switched texture loading order so diffuse is always first

- lib/loadObj.js
Fixes https://github.com/AnalyticalGraphicsInc/obj2gltf/issues/119
> Don't add a face that contains only two vertices

- CHANGES.md
- README.md
- bin/obj2gltf.js
> Fix output name

- lib/writeUris.js
- package.json
Note, this PR is into the 1.0 branch.  Since some people are still using 1.0 for glTF 1.x support, this bumps npm dependencies to their latest versions. Only `mime` required a minor code change on our end.
> Update npm modules

- bin/obj2gltf.js
Gives more helpful error messages if `-i` or `-o` are passed to the command line but are not followed by a filename.
Example: `obj2gtlf -i file.obj -o` will print `Output path must be a filename`
Example: `obj2gtlf -i` will print `Input path is required`
I'd prefer if this check could be done from the yargs side. Does anyone know if yargs can demand a string option to be greater than zero length?
> Handle empty -i -o arguments in CLI

- CHANGES.md
- lib/loadImage.js
- specs/lib/loadImageSpec.js
Fixes https://github.com/AnalyticalGraphicsInc/obj2gltf/issues/143
> load greyscale images as luminance instead of alpha

- CHANGES.md
- lib/loadObj.js
- package.json
- specs/lib/loadObjSpec.js
Fixes a bug introduced in https://github.com/AnalyticalGraphicsInc/obj2gltf/pull/153 where the vertex count was not getting reset properly when an obj has interleaved materials.
> Fix objs with interleaved materials

- .eslintrc.json
- CHANGES.md
- gulpfile.js
- lib/loadObj.js
- package.json
- specs/lib/loadObjSpec.js
Fixes https://github.com/AnalyticalGraphicsInc/obj2gltf/issues/147 by updating to the latest triangulation code used in Cesium. This fixes a model that wasn't triangulating correctly in `master`. This fix required updating Cesium so I updated other dependencies with it.
[csxirc5h.i2b.obj](https://drive.google.com/a/cesium.com/file/d/1B37hbNX2o9o6BM310z3gd8509SidFV-C/view?usp=sharing)
Before and after:
There are still some back facing polygons but I confirmed they are present in the original model too. We don't yet do that sort of correction.
(Backfacing polygons on the steps)
I checked that the new method still triangulates these models correctly:
https://github.com/AnalyticalGraphicsInc/obj2gltf/issues/33
https://github.com/AnalyticalGraphicsInc/obj2gltf/issues/50 …
> Update triangulation algorithm

- CHANGES.md
- lib/loadObj.js
- specs/lib/loadObjSpec.js
Improves on https://github.com/AnalyticalGraphicsInc/obj2gltf/pull/153 which deleted faces with mismatching attributes. 
Now those faces are either added to an existing primitive with that same material/attribute combo or are added to a new primitive.
This doesn't actually fix a tracked bug but may prevent future bugs.
To do:
> Keep mixed attributes

- gulpfile.js
- package.json
`gulp.task` was replaced with `module.exports` but no other changes were required.
> Upgrade to gulp4

- CHANGES.md
- lib/createGltf.js
- lib/writeGltf.js
- specs/lib/createGltfSpec.js
- specs/lib/obj2gltfSpec.js
Checks if the combined bin section of the glTF would exceed the Node buffer size limit (~2GB). If it does don't combine the accessors together, instead save them as separate .bin files.
It should be pretty unlikely that a single accessor would ever exceed 2GB. The obj reader splits the data up after every  `1000000` vertices to avoid exploding the vertex cache.
> Separate resources no longer hit Node buffer size limit

- lib/loadMtl.js
- specs/lib/loadMtlSpec.js
Some materials seem to have the diffuse and alpha textures set to the same file, so no need to combine them. Also added a test.
> Short circuits the image combining if diffuse and alpha textures are the same

- CHANGES.md
- LICENSE.md
- README.md
- package.json
Part of the CesiumGS github migration.
See https://groups.google.com/forum/?hl=en#!topic/cesium-dev/5sFSChDEtCg
Note: links to https://github.com/CesiumGS/cesium will only work once cesium is transferred over.
> Change links from AnalyticalGraphicsInc to CesiumGS

- CHANGES.md
- lib/createGltf.js
Fixes https://github.com/CesiumGS/obj2gltf/issues/239
This lets the runtime engine use the filtering modes they prefer. From the glTF spec:
> Default Filtering Implementation Note: When filtering options are defined, runtime must use them. Otherwise, it is free to adapt filtering to performance or quality goals.
> Remove minFilter and magFilter

- .editorconfig
- .eslintrc.json
- .gitignore
- .npmignore
- .prettierignore
- .travis.yml
- package.json
- Follows the same conventions as CesiumJS.
- Doesn't actually run the formatter or install the pre-commit hook yet.
- The changes can be viewed here: https://github.com/CesiumGS/obj2gltf/compare/prettier-test?expand=1
Steps for migrating to prettier will be as follows:
1. Merge this into master
1. Add a `pre-prettier` tag
1. Actually run prettier and commit the code changes to master
1. Add a `post-prettier` tag
1. Open a follow-up PR to add the pre-commit hooks for running prettier
Recommendations for how to update your branches can be found here: https://community.cesium.com/t/cesiumjs-source-code-is-now-formatted-with-prettier/9362
> Switch to prettier for formatting

- CHANGES.md
- lib/readLines.js
While testing out Node 16.9.0 for https://github.com/CesiumGS/obj2gltf/issues/266 I noticed that missing mtl files were not being handled gracefully anymore. Both unit tests and command line conversions were failing.
```sh
slilley@Lithium:~/Code/obj2gltf$ node bin/obj2gltf.js -i ./specs/data/box-missing-mtllib/box-missing-mtllib.obj -o ~/Desktop/test.gltf
node:events:371
throw er; // Unhandled 'error' event
^
Error: ENOENT: no such file or directory, open '/box.mtl'
Emitted 'error' event on Interface instance at:
at ReadStream.onerror (node:readline:265:10)
at ReadStream.emit (node:events:406:35)
at emitErrorNT (node:internal/streams/destroy:157:8)
at emitErrorCloseNT (node:internal/streams/destroy:122:3)
at processTicksAndRejections (node:internal/process/task_queues:83:21) {
errno: -2, …
```
> Fix unhandled error when mtl is missing

- CHANGES.md
- lib/createGltf.js
We have a couple areas in obj2gltf and gltf-pipeline that prevent merging buffers if the combined buffer would be greater than Node's maximum buffer size. This size was increased to 4,294,967,296 (2^32) bytes a little while back for 64-bit platforms.
The problem is fs.write has a separate maximum of 2,147,479,552 bytes which is the limit of the Linux [`write`](https://man7.org/linux/man-pages/man2/write.2.html) syscall. Node will throw an error if the buffer being written is greater than that value (actually, it checks if the value is a valid Int32 which is a slightly larger value).
So really we need to observe the fs.write limit.
See also: https://github.com/CesiumGS/gltf-pipeline/pull/627
> Don't merge buffers if final buffer exceeds fs.write maximum of `2147479552` bytes

- package.json
obj2gltf depends on CesiumJS which requires Node 14
> Require Node 14

- bin/obj2gltf.js
- gulpfile.js
- lib/ArrayStorage.js
- lib/createGltf.js
- lib/loadMtl.js
- lib/loadObj.js
- lib/obj2gltf.js
- lib/writeGltf.js
- package.json
- specs/lib/createGltfSpec.js
- specs/lib/loadMtlSpec.js
- specs/lib/loadObjSpec.js
- specs/lib/obj2gltfSpec.js
This is all internal dev stuff, not need to publish a new version or otherwise update anything.
* Upgrade prettier to 3.0.3 and format files.
* Upgrade `eslint-config-cesium` and `eslint-config-prettier`.
* Switch from the defunct `eslint-plugin-node` to `eslint-plugin-n` Since that is what `eslint-config-cesium` now uses.
* Switch from pretty-quick to lint-staged
> Monthly Maintenance

- CHANGES.md
- lib/loadMtl.js
- lib/loadObj.js
- package.json
If the mtl and/or texture paths are enclosed in double-quotes, they will fail to be read.
For example, if within the`obj` file, the mtl path is defined as follows:
`mtllib "OBJ - Berlin Bridge.mtl"`
The `mtl` file will not be loaded because when we try to compare the extension of the file to confirm that it ends with `.mtl`, that fails because the last token is `.mtl"`
The same thing happens to texture files.
This pull request strips the mtl and texture file of its double quotes if they exists. If they don't , nothing happens. 
There is at least one OBJ export tool (metashape from agisoft) that adds double quotes to filemanes that contains spaces in them.
This pull request sould fix this isse.
> Remove double quotes in the mtl and texture paths
